version: '3.8'
services:
  app:
    build: .
    restart: always
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      #- ./pgdata:/var/lib/postgresql/
      - ./flights.csv:/tmp/flights.csv
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  loaddata:
    image: postgres:14-alpine
    restart: on-failure
    depends_on:
      - app
      - postgres
    ports:
      - 5435:5432
    volumes:
      - ./flights.csv:/tmp/flights.csv
    command: psql -U ${DB_USER} -d ${DB_NAME} -h postgres  -c "\COPY Flights(ID,Name,Tail_number,Flight_number,Departure_city,Destination_city,Seats,Seats_left,Business_class_price,Economy_class_price,Flight_date)\ FROM '/tmp/flights.csv' \ DELIMITER ',' \ CSV HEADER;"
    environment:
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}